// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA1816:Dispose methods should call SuppressFinalize", Justification = "No unmanaged resources, so no need to call supress.", Scope = "member", Target = "~M:ConsoleOut.Net.Http.Intercepting.Test.TestFixture.Dispose")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "The default behavior is desired.", Scope = "member", Target = "~M:ConsoleOut.Net.Http.Intercepting.Test.RequestInterceptorTests.ShouldMockBadRequest~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "The default behavior is desired.", Scope = "member", Target = "~M:ConsoleOut.Net.Http.Intercepting.Test.RequestInterceptorTests.ShouldMockComplexRoute(System.String,System.String)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "The default behavior is desired.", Scope = "member", Target = "~M:ConsoleOut.Net.Http.Intercepting.Test.RequestInterceptorTests.ShouldMockGet(System.String)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "The default behavior is desired.", Scope = "member", Target = "~M:ConsoleOut.Net.Http.Intercepting.Test.RequestInterceptorTests.ShouldMockInternalServerError~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "The default behavior is desired.", Scope = "member", Target = "~M:ConsoleOut.Net.Http.Intercepting.Test.RequestInterceptorTests.ShouldMockNotFount~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "The default behavior is desired.", Scope = "member", Target = "~M:ConsoleOut.Net.Http.Intercepting.Test.RequestInterceptorTests.ShouldMockRoute(System.String,System.String)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "The default behavior is desired.", Scope = "member", Target = "~M:ConsoleOut.Net.Http.Intercepting.Test.RequestInterceptorTests.ShouldThrowHttpRequestExceptionForNotInterecptedRoute~System.Threading.Tasks.Task")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2234:Pass system uri objects instead of strings", Justification = "Ignore", Scope = "member", Target = "~M:ConsoleOut.Net.Http.Intercepting.Test.RequestInterceptorTests.ShouldMockBadRequest~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2234:Pass system uri objects instead of strings", Justification = "Ignore", Scope = "member", Target = "~M:ConsoleOut.Net.Http.Intercepting.Test.RequestInterceptorTests.ShouldMockComplexRoute(System.String,System.String)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2234:Pass system uri objects instead of strings", Justification = "Ignore", Scope = "member", Target = "~M:ConsoleOut.Net.Http.Intercepting.Test.RequestInterceptorTests.ShouldMockGet(System.String)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2234:Pass system uri objects instead of strings", Justification = "Ignore", Scope = "member", Target = "~M:ConsoleOut.Net.Http.Intercepting.Test.RequestInterceptorTests.ShouldMockInternalServerError~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2234:Pass system uri objects instead of strings", Justification = "Ignore", Scope = "member", Target = "~M:ConsoleOut.Net.Http.Intercepting.Test.RequestInterceptorTests.ShouldMockNotFount~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2234:Pass system uri objects instead of strings", Justification = "Ignore", Scope = "member", Target = "~M:ConsoleOut.Net.Http.Intercepting.Test.RequestInterceptorTests.ShouldMockRoute(System.String,System.String)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2234:Pass system uri objects instead of strings", Justification = "Ignore", Scope = "member", Target = "~M:ConsoleOut.Net.Http.Intercepting.Test.RequestInterceptorTests.ShouldThrowHttpRequestExceptionForNotInterecptedRoute~System.Threading.Tasks.Task")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "HttpClient will be dispoded in TestFixture.Dispose call.", Scope = "member", Target = "~M:ConsoleOut.Net.Http.Intercepting.Test.RequestInterceptorTests.ShouldMockBadRequest~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "HttpClient will be dispoded in TestFixture.Dispose call.", Scope = "member", Target = "~M:ConsoleOut.Net.Http.Intercepting.Test.RequestInterceptorTests.ShouldMockComplexRoute(System.String,System.String)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "HttpClient will be dispoded in TestFixture.Dispose call.", Scope = "member", Target = "~M:ConsoleOut.Net.Http.Intercepting.Test.RequestInterceptorTests.ShouldMockGet(System.String)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "HttpClient will be dispoded in TestFixture.Dispose call.", Scope = "member", Target = "~M:ConsoleOut.Net.Http.Intercepting.Test.RequestInterceptorTests.ShouldMockInternalServerError~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "HttpClient will be dispoded in TestFixture.Dispose call.", Scope = "member", Target = "~M:ConsoleOut.Net.Http.Intercepting.Test.RequestInterceptorTests.ShouldMockNotFount~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "HttpClient will be dispoded in TestFixture.Dispose call.", Scope = "member", Target = "~M:ConsoleOut.Net.Http.Intercepting.Test.RequestInterceptorTests.ShouldMockRoute(System.String,System.String)~System.Threading.Tasks.Task")]


